### ISSUE TITLE
clicking read / write on the relay screen gives an error

### ISSUE THREAD

**Issue by melvincarvalho** [v0l/snort#61]
## Bug

clicking read / write on the relay screen gives an error

For new and existing relays

![image](https://user-images.githubusercontent.com/65864/212502370-7b2bf991-84d1-4db6-a447-d14121c13687.png)

## Console debug:

```
Login.js:102 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at setRelays (Login.js:102:1)
    at createReducer.ts:294:1
    at produce (immerClass.ts:94:1)
    at createReducer.ts:293:1
    at Array.reduce (<anonymous>)
    at reducer (createReducer.ts:260:1)
    at reducer (createSlice.ts:372:1)
    at combination (redux.js:560:1)
    at dispatch (redux.js:288:1)
```

Seems to point to 

```JavaScript
let filtered = Object.entries(relays)
                .filter(a => a[0].startsWith("ws://") || a[0].startsWith("wss://"));
```

## To reproduce

Go to : https://snort.social/settings

Click any of the Read / Write Buttons

**Comment by v0l** [comment]
This should be fixed now!
